name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build Vue project
        run: npm run build

      - name: Upload static site
        uses: actions/upload-pages-artifact@v4
        with:
          path: "dist"   # The path to the directory containing the built static site files. Adjust this if your build output is in a different directory.  

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
